export interface AIModel {
  id: string;
  name: string;
  provider: string;
  description: string;
  detailDescription?: string;
  sourceUrl?: string;
  tags: string[];
  color: string;
  iconName: string;
  isFeatured?: boolean;
  // 가격 정보 (1천 토큰당 원화)
  pricing?: {
    input: number;  // 입력 1천 토큰당 원
    output: number; // 출력 1천 토큰당 원
  };
}

// 웍스AI 대표 모델 7종
export const featuredModelIds = [
  "gpt-5-2",
  "gemini-3-pro",
  "claude-opus-4-5",
  "solar-pro-3",
  "k-exaone-236b",
  "nano-banana-pro",
  "gemini-deep-research",
];

// OpenAI 모델 (19종)
export const openaiModels: AIModel[] = [
  {
    id: "gpt-5-2",
    name: "GPT-5.2",
    provider: "OpenAI",
    description: "장문 문서, 코드, 에이전트 처리에 최적화된 최신 플래그십 모델",
    detailDescription: "GPT-5.2는 OpenAI의 최신 플래그십 모델로, 장문의 문서 처리, 복잡한 코드 생성, 그리고 자율 에이전트 작업에 최적화되어 있습니다. 이전 세대 대비 컨텍스트 윈도우가 대폭 확장되었으며, 멀티스텝 추론 능력이 크게 향상되었습니다. 특히 복잡한 비즈니스 로직을 이해하고 구현하는 능력이 뛰어나며, 여러 파일에 걸친 대규모 코드베이스도 일관성 있게 처리할 수 있습니다.",
    sourceUrl: "https://openai.com/index/introducing-gpt-5-2/",
    tags: ["대표 모델", "자동 작업", "코딩"],
    color: "#000000",
    iconName: "Sparkles",
    pricing: { input: 6.431, output: 51.45 },
  },
  {
    id: "gpt-5-2-pro",
    name: "GPT-5.2 Pro",
    provider: "OpenAI",
    description: "5.2의 성능을 극한으로 끌어올려 전문가용 데이터 분석 및 연구에 특화",
    detailDescription: "GPT-5.2 Pro는 GPT-5.2의 성능을 극한으로 끌어올린 전문가용 모델입니다. 대규모 데이터셋 분석, 학술 연구 지원, 복잡한 통계 처리에 특화되어 있으며, 과학 논문 수준의 정확도로 정보를 분석하고 인사이트를 도출합니다. 금융, 의료, 연구 기관에서 전문적인 데이터 분석 업무에 활용하기에 최적화되어 있습니다.",
    sourceUrl: "https://openai.com/index/gpt-5-2-pro/",
    tags: ["전문가용", "연구", "데이터 분석"],
    color: "#000000",
    iconName: "GraduationCap",
    pricing: { input: 77.175, output: 617.4 },
  },
  {
    id: "gpt-5-2-chat",
    name: "GPT-5.2 Chat",
    provider: "OpenAI",
    description: "5.2 엔진을 대화형 인터페이스에 맞춰 튜닝한 자연어 소통 최적화 모델",
    detailDescription: "GPT-5.2 Chat은 GPT-5.2 엔진을 대화형 인터페이스에 맞게 미세 조정한 모델입니다. 자연스러운 대화 흐름, 문맥 이해, 사용자 의도 파악에 뛰어나며, 복잡한 멀티턴 대화에서도 일관성을 유지합니다. 고객 상담, 교육용 튜터링, 개인 비서 역할에 최적화되어 있습니다.",
    sourceUrl: "https://openai.com/chatgpt/",
    tags: ["대화", "질문응답", "상담"],
    color: "#000000",
    iconName: "MessageSquare",
  },
  {
    id: "gpt-5-1",
    name: "GPT-5.1",
    provider: "OpenAI",
    description: "적응형 추론(Adaptive Reasoning)으로 속도와 깊이를 스스로 조절하는 범용 모델",
    detailDescription: "GPT-5.1은 적응형 추론(Adaptive Reasoning) 기술을 탑재한 혁신적인 모델입니다. 문제의 복잡도에 따라 사고의 깊이와 응답 속도를 자동으로 조절하여, 간단한 질문에는 빠르게, 복잡한 문제에는 깊이 있게 대응합니다. 다양한 도메인에서 균형 잡힌 성능을 보여주는 범용 모델입니다.",
    sourceUrl: "https://openai.com/index/gpt-5-1/",
    tags: ["똑똑한 판단", "문제 해결", "만능"],
    color: "#000000",
    iconName: "Brain",
  },
  {
    id: "gpt-5-1-chat",
    name: "GPT-5.1 Chat",
    provider: "OpenAI",
    description: "5.1 기반의 대화 최적화 버전, 복잡한 프롬프트 지시 이행 능력 강화",
    detailDescription: "GPT-5.1 Chat은 GPT-5.1을 기반으로 대화 성능을 최적화한 모델입니다. 특히 복잡한 프롬프트와 상세한 지시사항을 정확하게 이행하는 능력이 강화되었습니다. 시스템 프롬프트의 세부 사항을 놓치지 않고 따르며, 멀티스텝 지시도 순서대로 정확하게 수행합니다.",
    sourceUrl: "https://openai.com/chatgpt/",
    tags: ["대화", "지시 수행", "복잡한 요청"],
    color: "#000000",
    iconName: "MessageSquare",
  },
  {
    id: "gpt-5",
    name: "GPT-5",
    provider: "OpenAI",
    description: "AGI에 근접한 지식과 상식 추론 능력을 갖춘 5세대의 표준 파운데이션",
    detailDescription: "GPT-5는 OpenAI 5세대 모델의 표준 파운데이션으로, AGI(범용 인공지능)에 가장 근접한 지식과 상식 추론 능력을 갖추고 있습니다. 인간 수준의 상식적 판단, 폭넓은 지식 베이스, 논리적 사고 능력을 보유하며, 다양한 분야에서 전문가 수준의 응답을 제공합니다.",
    sourceUrl: "https://openai.com/index/hello-gpt-5/",
    tags: ["기본 모델", "높은 지능", "폭넓은 지식"],
    color: "#000000",
    iconName: "Cpu",
  },
  {
    id: "gpt-5-chat",
    name: "GPT-5 Chat",
    provider: "OpenAI",
    description: "일반 사용자용으로 안전성과 응답 톤을 조정한 대화 특화 모델",
    detailDescription: "GPT-5 Chat은 일반 사용자를 위해 안전성과 응답 톤이 조정된 대화 특화 모델입니다. 유해 콘텐츠 필터링이 강화되어 있으며, 친근하고 이해하기 쉬운 언어로 응답합니다. 가족 친화적인 환경에서도 안심하고 사용할 수 있도록 설계되었습니다.",
    sourceUrl: "https://openai.com/chatgpt/",
    tags: ["대화", "안전함", "누구나 사용"],
    color: "#000000",
    iconName: "MessageSquare",
  },
  {
    id: "o4-mini",
    name: "o4 mini",
    provider: "OpenAI",
    description: "코딩 및 수학 문제를 저비용 고속으로 해결하는 가성비 추론 모델",
    detailDescription: "o4 mini는 코딩과 수학 문제 해결에 특화된 가성비 추론 모델입니다. o-시리즈의 논리적 추론 능력을 유지하면서도 비용은 대폭 낮추고 응답 속도는 높였습니다. 알고리즘 문제, 수학 증명, 코드 디버깅 등 논리적 사고가 필요한 작업에 최적화되어 있습니다.",
    sourceUrl: "https://openai.com/index/openai-o4-mini/",
    tags: ["논리 문제", "수학", "저렴함"],
    color: "#000000",
    iconName: "Calculator",
  },
  {
    id: "o3-pro",
    name: "o3 Pro",
    provider: "OpenAI",
    description: "심층 사고 시간을 늘려 과학 연구 및 고난도 논리 설계에 특화된 전문가용",
    detailDescription: "o3 Pro는 심층 사고 시간을 대폭 늘려 과학 연구와 고난도 논리 설계에 특화된 전문가용 모델입니다. 복잡한 과학적 가설 검증, 수학적 증명, 시스템 아키텍처 설계 등 깊은 사고가 필요한 작업에서 탁월한 성능을 보여줍니다. 연구소와 대학에서 주로 활용됩니다.",
    sourceUrl: "https://openai.com/index/introducing-o3-and-o4-mini/",
    tags: ["전문가용", "과학 연구", "깊은 생각"],
    color: "#000000",
    iconName: "Atom",
  },
  {
    id: "o3",
    name: "o3",
    provider: "OpenAI",
    description: "CoT(사고 사슬) 기술을 고도화하여 복잡한 문제를 오류 없이 풀어내는 추론 모델",
    detailDescription: "o3는 Chain-of-Thought(사고 사슬) 기술을 고도화한 추론 모델입니다. 복잡한 문제를 단계별로 분해하여 해결하며, 각 단계에서 자체 검증을 수행하여 오류를 최소화합니다. 논리 퍼즐, 프로그래밍 문제, 수학 문제에서 높은 정확도를 보여줍니다.",
    sourceUrl: "https://openai.com/index/introducing-o3-and-o4-mini/",
    tags: ["단계별 사고", "논리 문제", "정확함"],
    color: "#000000",
    iconName: "GitBranch",
  },
  {
    id: "o3-mini",
    name: "o3 Mini",
    provider: "OpenAI",
    description: "o3의 논리력을 유지하며 속도를 높인 실시간 학습 및 코딩 보조 모델",
    detailDescription: "o3 Mini는 o3의 논리적 추론 능력을 유지하면서 응답 속도를 크게 향상시킨 모델입니다. 실시간 학습 지원, 코딩 보조, 빠른 문제 해결이 필요한 상황에 적합합니다. IDE 통합, 실시간 코드 리뷰 등 인터랙티브한 개발 환경에서 특히 유용합니다.",
    sourceUrl: "https://openai.com/index/openai-o3-mini/",
    tags: ["소형", "빠름", "코딩 도우미"],
    color: "#000000",
    iconName: "Zap",
  },
  {
    id: "o1",
    name: "o1",
    provider: "OpenAI",
    description: "답변 전 심층 사고 과정을 거쳐 논리적 정확성을 획기적으로 높인 추론 모델의 시초",
    detailDescription: "o1은 OpenAI의 추론 모델 시리즈의 시초입니다. 답변을 생성하기 전에 내부적으로 심층 사고 과정을 거쳐 논리적 정확성을 획기적으로 높였습니다. 이 혁신적인 접근 방식은 이후 o-시리즈 모델들의 기반이 되었으며, AI 추론 연구의 새로운 방향을 제시했습니다.",
    sourceUrl: "https://openai.com/index/introducing-openai-o1-preview/",
    tags: ["최초 모델", "깊은 생각", "논리적"],
    color: "#000000",
    iconName: "Lightbulb",
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini",
    provider: "OpenAI",
    description: "GPT-5의 지능을 유지하며 비용을 낮춘 상용 서비스 표준 경량 모델",
    detailDescription: "GPT-5 Mini는 GPT-5의 지능 수준을 유지하면서 비용 효율성을 극대화한 경량 모델입니다. 상용 서비스의 표준 모델로 자리 잡았으며, 합리적인 비용으로 높은 품질의 AI 서비스를 제공하고자 하는 기업들에게 최적의 선택입니다.",
    sourceUrl: "https://openai.com/index/gpt-5-mini/",
    tags: ["소형", "저렴함", "실용적"],
    color: "#000000",
    iconName: "Minimize2",
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano",
    provider: "OpenAI",
    description: "모바일 및 로컬 환경 구동을 위해 극도로 경량화된 초소형 온디바이스 모델",
    detailDescription: "GPT-5 Nano는 모바일 기기와 로컬 환경에서 구동할 수 있도록 극도로 경량화된 온디바이스 모델입니다. 인터넷 연결 없이도 스마트폰, 태블릿, 엣지 디바이스에서 AI 기능을 활용할 수 있습니다. 프라이버시가 중요한 상황이나 오프라인 환경에서 특히 유용합니다.",
    sourceUrl: "https://openai.com/index/gpt-5-nano/",
    tags: ["초소형", "휴대폰 사용", "인터넷 불필요"],
    color: "#000000",
    iconName: "Smartphone",
  },
  {
    id: "gpt-4-1-mini",
    name: "GPT-4.1 Mini",
    provider: "OpenAI",
    description: "이전 세대 아키텍처 기반의 고효율 저비용 텍스트 처리 모델",
    detailDescription: "GPT-4.1 Mini는 검증된 GPT-4 아키텍처를 기반으로 한 고효율 텍스트 처리 모델입니다. 안정적인 성능과 낮은 비용으로 대량의 텍스트 처리 작업에 적합합니다. 콘텐츠 생성, 요약, 번역 등 일반적인 텍스트 작업에서 뛰어난 가성비를 제공합니다.",
    sourceUrl: "https://openai.com/index/gpt-4-1/",
    tags: ["소형", "효율적", "글 작성"],
    color: "#000000",
    iconName: "FileText",
  },
  {
    id: "gpt-4-1-nano",
    name: "GPT-4.1 Nano",
    provider: "OpenAI",
    description: "인터넷 연결 없는 엣지 디바이스에서도 구동 가능한 오프라인용 모델",
    detailDescription: "GPT-4.1 Nano는 엣지 디바이스와 오프라인 환경을 위해 설계된 초경량 모델입니다. IoT 기기, 임베디드 시스템, 네트워크 연결이 불안정한 환경에서 안정적으로 작동합니다. 실시간 처리가 필요한 산업 현장이나 원격지 환경에서 활용됩니다.",
    sourceUrl: "https://openai.com/index/gpt-4-1/",
    tags: ["초소형", "인터넷 불필요", "소형 기기"],
    color: "#000000",
    iconName: "WifiOff",
  },
  {
    id: "gpt-4-1",
    name: "GPT-4.1",
    provider: "OpenAI",
    description: "GPT-4o의 아키텍처를 개량하여 안정성과 신뢰성을 높인 텍스트 모델",
    detailDescription: "GPT-4.1은 GPT-4o의 아키텍처를 개량하여 안정성과 신뢰성을 한층 높인 모델입니다. 기업 환경에서 요구하는 일관된 출력 품질, 낮은 할루시네이션 비율, 예측 가능한 동작을 제공합니다. 프로덕션 환경에서 안정적인 서비스 운영이 필요한 경우에 적합합니다.",
    sourceUrl: "https://openai.com/index/gpt-4-1/",
    tags: ["안정적", "믿을 수 있음", "글 작성"],
    color: "#000000",
    iconName: "Shield",
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    provider: "OpenAI",
    description: "텍스트·음성·이미지를 실시간으로 처리하는 옴니(Omni) 기능을 갖춘 4세대 표준",
    detailDescription: "GPT-4o(Omni)는 텍스트, 음성, 이미지를 실시간으로 통합 처리하는 멀티모달 모델입니다. 음성 대화, 이미지 분석, 텍스트 생성을 하나의 모델에서 자연스럽게 수행하며, 실시간 상호작용이 가능합니다. 대화형 AI 어시스턴트의 새로운 기준을 제시한 모델입니다.",
    sourceUrl: "https://openai.com/index/hello-gpt-4o/",
    tags: ["통합형", "글+이미지+음성", "실시간"],
    color: "#000000",
    iconName: "Layers",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "OpenAI",
    description: "4o의 멀티모달 기능을 가장 저렴하게 제공하여 대중화를 이끈 가성비 모델",
    detailDescription: "GPT-4o Mini는 GPT-4o의 멀티모달 기능을 저렴한 가격에 제공하여 AI 대중화를 이끈 모델입니다. 이미지 인식, 텍스트 생성, 기본적인 음성 처리를 합리적인 비용으로 이용할 수 있습니다. 스타트업과 개인 개발자들이 멀티모달 AI를 서비스에 통합하기에 최적의 선택입니다.",
    sourceUrl: "https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/",
    tags: ["소형", "글+이미지", "저렴함"],
    color: "#000000",
    iconName: "DollarSign",
  },
];

// Google 모델 (7종)
export const googleModels: AIModel[] = [
  {
    id: "gemini-3-pro",
    name: "Gemini 3.0 Pro",
    provider: "Google",
    description: "Deep Think 모드와 압도적 멀티모달 분석력을 갖춘 구글의 최상위 에이전트",
    detailDescription: "Gemini 3.0 Pro는 Google의 최상위 AI 모델로, Deep Think 모드를 통해 복잡한 문제에 대한 심층적인 분석이 가능합니다. 텍스트, 이미지, 비디오, 오디오를 통합적으로 이해하고 처리하는 압도적인 멀티모달 분석력을 갖추고 있으며, 자율 에이전트로서 복잡한 작업을 독립적으로 수행할 수 있습니다. 과학 연구, 비즈니스 분석, 창작 활동 등 다양한 영역에서 최고 수준의 성능을 제공합니다.",
    sourceUrl: "https://deepmind.google/technologies/gemini/",
    tags: ["깊은 생각", "글+이미지", "자동 작업"],
    color: "#4285F4",
    iconName: "Brain",
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "Google",
    description: "4K급 상업용 이미지 생성 및 정밀 편집에 특화된 크리에이티브 모델",
    detailDescription: "Nano Banana Pro는 Google의 최신 이미지 생성 모델로, 4K 해상도의 상업용 품질 이미지를 생성할 수 있습니다. 정밀한 이미지 편집, 스타일 변환, 부분 수정 등 크리에이티브 작업에 특화되어 있으며, 광고, 마케팅, 디자인 분야에서 전문가 수준의 결과물을 제공합니다. Imagen 3 기술을 기반으로 포토리얼리스틱한 이미지 생성이 가능합니다.",
    sourceUrl: "https://deepmind.google/technologies/imagen-3/",
    tags: ["이미지 생성", "고화질", "창작"],
    color: "#4285F4",
    iconName: "Image",
  },
  {
    id: "gemini-deep-research",
    name: "Gemini Deep Research",
    provider: "Google",
    description: "멀티모달 입력을 지원하며 웹을 심층 탐색해 구조화된 보고서와 시각 자료를 생성하는 AI 리서치 에이전트",
    detailDescription: "Gemini Deep Research는 Google의 AI 리서치 에이전트로, 웹을 심층 탐색하여 포괄적인 연구를 수행합니다. 텍스트, 이미지, 문서 등 다양한 멀티모달 입력을 지원하며, 수백 개의 소스를 분석하여 구조화된 보고서와 시각 자료를 자동으로 생성합니다. 학술 연구, 시장 조사, 경쟁사 분석 등 심층적인 리서치가 필요한 작업에 최적화되어 있습니다.",
    sourceUrl: "https://blog.google/products/gemini/google-gemini-deep-research/",
    tags: ["자료 조사", "보고서 작성", "정리"],
    color: "#4285F4",
    iconName: "FileSearch",
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3.0 Flash",
    provider: "Google",
    description: "높은 성능은 그대로 살리면서도 속도는 빠르게, 가격은 낮춘 최강 가성비 모델",
    detailDescription: "Gemini 3.0 Flash는 Gemini 3.0 Pro의 높은 성능을 유지하면서 응답 속도를 대폭 향상시키고 비용을 낮춘 최강의 가성비 모델입니다. 빠른 응답이 필요한 실시간 애플리케이션, 대량의 요청을 처리해야 하는 서비스에 적합하며, 품질 대비 비용 효율성이 뛰어납니다. 일반적인 비즈니스 애플리케이션에서 최적의 선택입니다.",
    sourceUrl: "https://deepmind.google/technologies/gemini/flash/",
    tags: ["빠름", "저렴함", "좋은 성능"],
    color: "#4285F4",
    iconName: "Zap",
  },
  {
    id: "gemini-2-5-pro",
    name: "Gemini 2.5 Pro",
    provider: "Google",
    description: "안정적인 코딩 성능과 추론 능력을 바탕으로 기업 표준으로 쓰이는 고성능 모델",
    detailDescription: "Gemini 2.5 Pro는 안정적인 코딩 성능과 뛰어난 추론 능력으로 기업 환경의 표준 모델로 자리 잡았습니다. 복잡한 코드 생성, 디버깅, 리팩토링에서 일관된 품질을 제공하며, 비즈니스 로직 분석과 의사결정 지원에도 탁월합니다. 엔터프라이즈 애플리케이션 개발과 운영에 최적화되어 있습니다.",
    sourceUrl: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/",
    tags: ["기업용", "코딩", "안정적"],
    color: "#4285F4",
    iconName: "Building",
  },
  {
    id: "gemini-2-5-flash",
    name: "Gemini 2.5 Flash",
    provider: "Google",
    description: "대량의 문서 및 긴 컨텍스트를 가장 빠르고 저렴하게 처리하는 가성비 모델",
    detailDescription: "Gemini 2.5 Flash는 대량의 문서와 긴 컨텍스트를 빠르고 저렴하게 처리하는 데 특화된 모델입니다. 100만 토큰 이상의 긴 컨텍스트 윈도우를 지원하며, 대규모 문서 분석, 요약, 정보 추출 작업에서 뛰어난 가성비를 제공합니다. 법률 문서, 연구 논문, 기술 문서 등 대용량 텍스트 처리에 최적입니다.",
    sourceUrl: "https://deepmind.google/technologies/gemini/flash/",
    tags: ["긴 문서", "대량 처리", "빠름"],
    color: "#4285F4",
    iconName: "FileStack",
  },
  {
    id: "gemini-2-5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "Google",
    description: "모바일 환경 및 단순 반복 작업에 최적화된 초경량 고속 모델",
    detailDescription: "Gemini 2.5 Flash Lite는 모바일 환경과 단순 반복 작업에 최적화된 초경량 모델입니다. 최소한의 리소스로 빠른 응답을 제공하며, 대량의 단순 요청을 효율적으로 처리합니다. 챗봇, 자동 분류, 간단한 텍스트 처리 등 경량 AI 기능이 필요한 애플리케이션에 적합합니다.",
    sourceUrl: "https://deepmind.google/technologies/gemini/flash/",
    tags: ["초경량", "휴대폰용", "빠름"],
    color: "#4285F4",
    iconName: "Smartphone",
  },
];

// Claude 모델 (8종)
export const claudeModels: AIModel[] = [
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    provider: "Anthropic",
    description: "현존 최고 지능, 복잡한 R&D 및 정교한 글쓰기에 최적화된 전문가용 모델",
    detailDescription: "Claude Opus 4.5는 Anthropic의 플래그십 모델로, 현존하는 AI 모델 중 가장 높은 지능 수준을 자랑합니다. 복잡한 연구개발 과제, 학술 논문 작성, 창작 문학 등 정교한 지적 작업에 최적화되어 있습니다. 뉘앙스 있는 표현, 깊이 있는 분석, 창의적인 문제 해결 능력에서 탁월한 성능을 보여주며, Constitutional AI 기술로 안전성과 유용성의 균형을 이룹니다.",
    sourceUrl: "https://www.anthropic.com/claude/opus",
    tags: ["최고 성능", "연구개발", "글쓰기"],
    color: "#D4A27F",
    iconName: "Crown",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "Anthropic",
    description: "Opus급 지능에 속도를 더해 실무 코딩 및 업무 자동화에 가장 적합한 모델",
    detailDescription: "Claude Sonnet 4.5는 Opus급의 지능에 빠른 응답 속도를 결합한 모델입니다. 실무 코딩, 업무 자동화, 대규모 코드베이스 분석에 가장 적합하며, 개발자들 사이에서 가장 인기 있는 코딩 AI로 자리 잡았습니다. 복잡한 소프트웨어 아키텍처를 이해하고, 버그를 찾아내며, 효율적인 코드를 생성하는 능력이 뛰어납니다.",
    sourceUrl: "https://www.anthropic.com/claude/sonnet",
    tags: ["코딩", "업무 자동화", "빠름"],
    color: "#D4A27F",
    iconName: "Code",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    description: "즉각적인 반응 속도와 준수한 지능을 갖춘 대고객 챗봇 및 번역용 모델",
    detailDescription: "Claude Haiku 4.5는 즉각적인 반응 속도와 준수한 지능을 갖춘 경량 모델입니다. 대고객 챗봇, 실시간 번역, 고속 텍스트 처리에 최적화되어 있으며, 비용 효율성이 뛰어납니다. 수백만 건의 요청을 처리해야 하는 대규모 서비스에서도 안정적인 성능을 제공합니다.",
    sourceUrl: "https://www.anthropic.com/claude/haiku",
    tags: ["즉시 응답", "고객 상담", "번역"],
    color: "#D4A27F",
    iconName: "MessageCircle",
  },
  {
    id: "claude-opus-4-1",
    name: "Claude Opus 4.1",
    provider: "Anthropic",
    description: "금융/법률 등 정밀성이 요구되는 분야를 위해 논리 안정성을 강화한 모델",
    detailDescription: "Claude Opus 4.1은 금융, 법률, 의료 등 정밀성이 요구되는 전문 분야를 위해 논리적 안정성을 강화한 모델입니다. 계약서 검토, 규정 준수 확인, 리스크 분석 등에서 일관되고 신뢰할 수 있는 결과를 제공합니다. 할루시네이션 비율을 최소화하고, 불확실한 정보에 대해서는 명확하게 표시합니다.",
    sourceUrl: "https://www.anthropic.com/claude",
    tags: ["금융", "법률", "정밀함"],
    color: "#D4A27F",
    iconName: "Scale",
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    provider: "Anthropic",
    description: "준수한 성능과 데이터 추출 능력으로 비즈니스 실무 표준으로 자리 잡은 모델",
    detailDescription: "Claude Sonnet 4는 균형 잡힌 성능과 뛰어난 데이터 추출 능력으로 비즈니스 실무의 표준 모델로 자리 잡았습니다. 구조화된 데이터 추출, 문서 분석, 이메일 자동 처리 등 일상적인 비즈니스 작업을 효율적으로 처리합니다. 다양한 기업 환경에서 검증된 안정성을 제공합니다.",
    sourceUrl: "https://www.anthropic.com/news/claude-4",
    tags: ["업무용", "데이터 정리", "실용적"],
    color: "#D4A27F",
    iconName: "Briefcase",
  },
  {
    id: "claude-opus-4",
    name: "Claude Opus 4",
    provider: "Anthropic",
    description: "긴 사고 과정을 통해 난해한 논리 퍼즐이나 수학적 검증을 수행하는 모델",
    detailDescription: "Claude Opus 4는 Extended Thinking 기능을 통해 긴 사고 과정을 거쳐 난해한 문제를 해결하는 모델입니다. 복잡한 논리 퍼즐, 수학적 증명, 알고리즘 설계 등에서 단계별로 사고를 전개하며 정확한 답을 도출합니다. 연구자와 수학자들이 복잡한 문제를 검증하는 데 활용합니다.",
    sourceUrl: "https://www.anthropic.com/news/claude-4",
    tags: ["논리 문제", "수학", "검증"],
    color: "#D4A27F",
    iconName: "Calculator",
  },
  {
    id: "claude-haiku-3-5",
    name: "Claude Haiku 3.5",
    provider: "Anthropic",
    description: "뉴스 요약 및 단순 분류 작업에 최고의 가성비를 보여주는 실무형 모델",
    detailDescription: "Claude Haiku 3.5는 뉴스 요약, 텍스트 분류, 감정 분석 등 단순하지만 대량의 처리가 필요한 작업에서 최고의 가성비를 제공합니다. 미디어, 마케팅, 고객 서비스 분야에서 대량의 콘텐츠를 효율적으로 처리하는 데 최적화되어 있습니다.",
    sourceUrl: "https://www.anthropic.com/news/claude-3-5-haiku",
    tags: ["요약", "분류", "저렴함"],
    color: "#D4A27F",
    iconName: "Newspaper",
  },
  {
    id: "claude-haiku-3",
    name: "Claude Haiku 3",
    provider: "Anthropic",
    description: "API 비용 최소화 및 테스트 환경에 적합한 초기 경량 모델",
    detailDescription: "Claude Haiku 3는 API 비용을 최소화하면서 기본적인 AI 기능을 제공하는 초기 경량 모델입니다. 개발 및 테스트 환경, 프로토타이핑, 비용에 민감한 애플리케이션에 적합합니다. 간단한 질의응답, 텍스트 생성, 기본적인 분석 작업을 저렴하게 수행할 수 있습니다.",
    sourceUrl: "https://www.anthropic.com/news/claude-3-haiku",
    tags: ["저렴함", "테스트용", "가벼움"],
    color: "#D4A27F",
    iconName: "Feather",
  },
];

// Perplexity 모델 (4종)
export const perplexityModels: AIModel[] = [
  {
    id: "sonar-deep-research",
    name: "Sonar Deep Research",
    provider: "Perplexity",
    description: "수백 개 소스를 자율 탐색 및 종합하여 심층 보고서를 작성하는 리서치 에이전트",
    detailDescription: "Sonar Deep Research는 Perplexity의 가장 강력한 리서치 에이전트입니다. 수백 개의 웹 소스를 자율적으로 탐색하고, 정보를 종합하여 구조화된 심층 보고서를 작성합니다. 학술 연구, 시장 조사, 경쟁 분석 등 복잡한 리서치 작업을 자동화하며, 출처를 명확하게 표시하여 신뢰성을 보장합니다.",
    sourceUrl: "https://www.perplexity.ai/hub/blog/introducing-perplexity-deep-research",
    tags: ["깊은 조사", "자동 검색", "보고서"],
    color: "#20808D",
    iconName: "Search",
  },
  {
    id: "sonar-reasoning-pro",
    name: "Sonar Reasoning Pro",
    provider: "Perplexity",
    description: "검색된 정보의 인과관계를 분석하고 검증하는 고지능 논리 검색 모델",
    detailDescription: "Sonar Reasoning Pro는 검색된 정보의 인과관계를 분석하고 검증하는 고지능 모델입니다. 단순히 정보를 찾는 것을 넘어, 정보 간의 논리적 연결을 파악하고, 모순되는 정보를 식별하며, 팩트체크를 수행합니다. 뉴스 분석, 학술 검증, 의사결정 지원에 적합합니다.",
    sourceUrl: "https://www.perplexity.ai/hub/blog/introducing-sonar-reasoning",
    tags: ["논리 분석", "사실 확인", "검증"],
    color: "#20808D",
    iconName: "GitBranch",
  },
  {
    id: "sonar-pro",
    name: "Sonar Pro",
    provider: "Perplexity",
    description: "방대한 검색 소스와 긴 문맥을 처리하여 포괄적인 답변을 제공하는 전문가용 검색 모델",
    detailDescription: "Sonar Pro는 방대한 검색 소스와 긴 문맥을 처리하여 포괄적인 답변을 제공하는 전문가용 모델입니다. 복잡한 질문에 대해 여러 관점을 종합하고, 최신 정보와 역사적 맥락을 함께 제공합니다. 전문 연구자, 저널리스트, 분석가들이 깊이 있는 정보 탐색에 활용합니다.",
    sourceUrl: "https://www.perplexity.ai/hub/blog/sonar-pro",
    tags: ["전문가용", "종합 검색", "긴 문서"],
    color: "#20808D",
    iconName: "Globe",
  },
  {
    id: "sonar",
    name: "Sonar",
    provider: "Perplexity",
    description: "웹 실시간 정보를 딜레이 없이 찾아주는 빠르고 가벼운 일반 검색용 모델",
    detailDescription: "Sonar는 웹의 실시간 정보를 딜레이 없이 찾아주는 빠르고 가벼운 검색 모델입니다. 일상적인 질문, 최신 뉴스 확인, 간단한 팩트체크 등에 최적화되어 있으며, 출처와 함께 명확한 답변을 즉시 제공합니다. Perplexity 검색 엔진의 핵심 모델입니다.",
    sourceUrl: "https://www.perplexity.ai/",
    tags: ["실시간", "빠른 검색", "가벼움"],
    color: "#20808D",
    iconName: "Zap",
  },
];

// xAI 모델 (6종)
export const xaiModels: AIModel[] = [
  {
    id: "grok-4-1-fast",
    name: "Grok 4.1 Fast",
    provider: "xAI",
    description: "속도도 빠르고 가격도 저렴, 성능도 좋은 일론 머스크 xAI의 최상위 모델",
    detailDescription: "Grok 4.1 Fast는 일론 머스크의 xAI가 개발한 최상위 모델입니다. 빠른 응답 속도, 저렴한 가격, 뛰어난 성능의 삼박자를 모두 갖추었습니다. X(구 트위터) 플랫폼과의 통합으로 실시간 정보에 접근할 수 있으며, 유머러스하고 솔직한 응답 스타일이 특징입니다. 범용 AI 어시스턴트로서 다양한 작업에 활용됩니다.",
    sourceUrl: "https://x.ai/",
    tags: ["빠름", "저렴함", "최고 성능"],
    color: "#000000",
    iconName: "Rocket",
  },
  {
    id: "grok-4-fast",
    name: "Grok 4 Fast",
    provider: "xAI",
    description: "4.1 이전 버전으로, 빠른 텍스트 요약 및 대화형 서비스에 적합한 고효율 모델",
    detailDescription: "Grok 4 Fast는 빠른 텍스트 요약과 대화형 서비스에 최적화된 고효율 모델입니다. Grok 특유의 위트 있는 응답 스타일을 유지하면서, 일상적인 질문과 대화에 빠르게 응답합니다. 고객 서비스, 콘텐츠 요약, 간단한 정보 조회에 적합합니다.",
    sourceUrl: "https://x.ai/",
    tags: ["빠름", "요약", "대화"],
    color: "#000000",
    iconName: "Zap",
  },
  {
    id: "grok-code-fast",
    name: "Grok Code Fast",
    provider: "xAI",
    description: "복잡한 추론보다 코드 생성 및 로직 이해에 자원을 집중한 개발 전용 모델",
    detailDescription: "Grok Code Fast는 코드 생성과 로직 이해에 특화된 개발자 전용 모델입니다. 복잡한 일반 추론보다 프로그래밍 작업에 자원을 집중하여, 코드 작성, 디버깅, 리팩토링에서 빠르고 정확한 결과를 제공합니다. 다양한 프로그래밍 언어를 지원하며, IDE 통합에 최적화되어 있습니다.",
    sourceUrl: "https://x.ai/",
    tags: ["코딩 전용", "개발자용", "프로그래밍"],
    color: "#000000",
    iconName: "Code",
  },
  {
    id: "grok-4",
    name: "Grok 4",
    provider: "xAI",
    description: "깊이 있는 답변과 위트 있는 표현이 가능한 xAI의 4세대 표준 플래그십",
    detailDescription: "Grok 4는 xAI의 4세대 표준 플래그십 모델입니다. 깊이 있는 분석, 창의적인 답변, 그리고 Grok 특유의 위트 있는 표현이 가능합니다. 복잡한 주제에 대해 다각도로 분석하고, 때로는 반어적이거나 유머러스한 방식으로 정보를 전달합니다. X 플랫폼의 실시간 데이터와 연동됩니다.",
    sourceUrl: "https://x.ai/",
    tags: ["대표 모델", "재치있음", "깊은 답변"],
    color: "#000000",
    iconName: "Sparkles",
  },
  {
    id: "grok-3",
    name: "Grok 3",
    provider: "xAI",
    description: "안정적인 챗봇 기능과 기본 정보 검색을 지원하는 무난한 이전 세대 모델",
    detailDescription: "Grok 3는 안정적인 챗봇 기능과 기본 정보 검색을 지원하는 이전 세대 모델입니다. 검증된 성능과 안정성으로 일반적인 대화형 서비스에 무난하게 사용할 수 있습니다. 비용 효율적인 운영이 필요한 서비스에 적합합니다.",
    sourceUrl: "https://x.ai/",
    tags: ["안정적", "대화", "검색"],
    color: "#000000",
    iconName: "MessageSquare",
  },
  {
    id: "grok-3-mini",
    name: "Grok 3 Mini",
    provider: "xAI",
    description: "개인 서버 구동 및 간단한 데이터 라벨링 처리에 적합한 초경량 모델",
    detailDescription: "Grok 3 Mini는 개인 서버나 로컬 환경에서 구동할 수 있는 초경량 모델입니다. 간단한 데이터 라벨링, 텍스트 분류, 기본적인 질의응답 등 단순 작업에 적합합니다. 리소스 제약이 있는 환경에서도 Grok의 기본 기능을 활용할 수 있습니다.",
    sourceUrl: "https://x.ai/",
    tags: ["소형", "가벼움", "단순 작업"],
    color: "#000000",
    iconName: "Minimize2",
  },
];

// Upstage 모델 (2종)
export const upstageModels: AIModel[] = [
  {
    id: "solar-pro-3",
    name: "Solar Pro 3",
    provider: "Upstage",
    description: "한국어와 영어 모두 뛰어난 Upstage 최신 모델. 긴 문서도 한 번에 읽고 정확하게 답변합니다.",
    detailDescription: "Solar Pro 3는 한국의 AI 스타트업 Upstage가 개발한 최신 대규모 언어 모델입니다. 한국어와 영어 모두에서 뛰어난 성능을 보여주며, 긴 문서를 한 번에 처리하고 정확한 답변을 제공합니다. 특히 한국어 문맥 이해와 자연스러운 표현에서 글로벌 모델들을 능가하는 성능을 보여줍니다. 기업 문서 처리, 고객 서비스, 콘텐츠 생성 등 다양한 분야에서 활용됩니다.",
    sourceUrl: "https://www.upstage.ai/solar-llm",
    tags: ["한국어", "영어", "긴 문서"],
    color: "#5046E5",
    iconName: "Sparkles",
  },
  {
    id: "solar-pro-2",
    name: "Solar Pro 2",
    provider: "Upstage",
    description: "한국어 처리 능력이 뛰어난 Upstage 소버린 AI 모델",
    detailDescription: "Solar Pro 2는 Upstage의 소버린 AI(Sovereign AI) 전략의 핵심 모델입니다. 한국어 처리 능력이 특히 뛰어나며, 한국 문화와 맥락에 대한 깊은 이해를 바탕으로 자연스러운 응답을 생성합니다. 국내 기업들의 AI 도입에 최적화되어 있으며, 데이터 주권과 보안이 중요한 환경에서 특히 가치를 발휘합니다.",
    sourceUrl: "https://www.upstage.ai/solar-llm",
    tags: ["한국어", "국산 AI", "문서"],
    color: "#5046E5",
    iconName: "Sun",
  },
];

// LG 모델 (3종)
export const lgModels: AIModel[] = [
  {
    id: "k-exaone-236b",
    name: "K-EXAONE 236B",
    provider: "LG",
    description: "LG가 만든 한국 대표 AI 모델. 글로벌 성능 Top 10에 진입한 국산 최강 모델입니다.",
    detailDescription: "K-EXAONE 236B는 LG AI연구원이 개발한 한국 대표 AI 모델입니다. 2,360억 개의 파라미터를 가진 초거대 언어 모델로, 글로벌 벤치마크에서 Top 10에 진입한 국산 최강 모델입니다. 한국어와 영어 모두에서 뛰어난 성능을 보여주며, 특히 전문 지식 영역에서 높은 정확도를 자랑합니다. LG 그룹의 다양한 사업 영역에서 활용되고 있습니다.",
    sourceUrl: "https://www.lgresearch.ai/exaone",
    tags: ["한국 대표", "세계 10위권", "LG"],
    color: "#A50034",
    iconName: "Trophy",
  },
  {
    id: "lg-exaone-4-0-1",
    name: "LG EXAONE 4.0.1",
    provider: "LG",
    description: "전문 분야(화학/바이오 등) 데이터 학습 및 추론 정밀도가 향상된 전문가용 모델",
    detailDescription: "LG EXAONE 4.0.1은 화학, 바이오, 소재 과학 등 전문 분야의 데이터를 집중 학습한 전문가용 모델입니다. LG화학, LG생활건강 등 LG 계열사의 R&D 데이터를 활용하여 해당 분야의 추론 정밀도를 크게 향상시켰습니다. 신약 개발, 소재 연구, 화학 공정 최적화 등 전문적인 과학 연구에 활용됩니다.",
    sourceUrl: "https://www.lgresearch.ai/exaone",
    tags: ["전문가용", "화학", "바이오"],
    color: "#A50034",
    iconName: "FlaskConical",
  },
  {
    id: "lg-exaone-4-0",
    name: "LG EXAONE 4.0",
    provider: "LG",
    description: "온디바이스와 서버 환경을 모두 지원하며 멀티모달 기능을 갖춘 산업용 모델",
    detailDescription: "LG EXAONE 4.0은 온디바이스와 서버 환경을 모두 지원하는 산업용 멀티모달 AI 모델입니다. 텍스트, 이미지, 문서를 통합적으로 처리할 수 있으며, 제조 현장, 스마트 팩토리, 품질 관리 등 산업 환경에 최적화되어 있습니다. 엣지 디바이스에서도 구동 가능하여 실시간 의사결정이 필요한 산업 현장에서 활용됩니다.",
    sourceUrl: "https://www.lgresearch.ai/exaone",
    tags: ["기기 내 실행", "글+이미지", "산업용"],
    color: "#A50034",
    iconName: "Factory",
  },
];

// 전체 모델 목록
export const aiModels: AIModel[] = [
  ...openaiModels,
  ...googleModels,
  ...claudeModels,
  ...perplexityModels,
  ...xaiModels,
  ...upstageModels,
  ...lgModels,
];

// Provider 목록
export const providers = [
  "웍스 대표 모델",
  "All",
  "OpenAI",
  "Google",
  "Anthropic",
  "Perplexity",
  "xAI",
  "Upstage",
  "LG",
];

// Provider별 색상 (브랜드 메인 컬러)
export const providerColors: Record<string, string> = {
  "웍스 대표 모델": "#5D5FEF",
  All: "#6B7280",
  OpenAI: "#000000",
  Google: "#4285F4",
  Anthropic: "#D4A27F",
  Perplexity: "#20808D",
  xAI: "#000000",
  Upstage: "#5046E5",
  LG: "#A50034",
};

// Provider별 로고 파일명 (public/logos/ 폴더에 저장)
export const providerLogos: Record<string, string> = {
  OpenAI: "openai.svg",
  Google: "gemini.png",
  Anthropic: "anthropic.png",
  Perplexity: "perplexity.png",
  xAI: "xai.png",
  Upstage: "upstage.svg",
  LG: "lg.png",
};
